bold_men/bold_men/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import HomePage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('contracts/', include('contracts.urls')),
    path('fabrics/', include('fabrics.urls')),
    path('orders/', include('orders.urls')),
    path('payments/', include('payments.urls')),
    path('measurements/', include('measurements.urls')),
    path('', HomePage.as_view(), name="home-page"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

bold_men/fabrics/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import FabricCreateView, FabricDeleteView, FabricDetailView, FabricListView, FabricUpdateView

app_name = "fabrics"

urlpatterns = [
    path('fabrics', FabricListView.as_view(), name='fabric-list'),
    path('fabric/new/', FabricCreateView.as_view(), name='fabric-create'),
    path('fabric/<int:pk>/', FabricDetailView.as_view(), name='fabric-detail'),
    path('fabric/<int:pk>/update', FabricUpdateView.as_view(), name='fabric-update'),
    path('fabric/<int:pk>/delete', FabricDeleteView.as_view(), name='fabric-delete'),
]

bold_men/orders/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "orders"

urlpatterns = [
    # path(),
]

bold_men/fabrics/models.py
from django.db import models

class Fabric(models.Model):
    """
    A Django model representing a type of fabric.

    Attributes:
        name (str): The name of the fabric.
        description (str): A description of the fabric.
        price (Decimal): The price of the fabric.
    """

    name = models.CharField(max_length=100, help_text="The name of the fabric.")
    description = models.TextField(help_text="A description of the fabric.")
    price = models.DecimalField(
        decimal_places=2, max_digits=10, help_text="The price of the fabric."
    )

    def __str__(self):
        """
        Returns the name of the fabric as its string representation.

        Returns:
            str: The name of the fabric.
        """
        return self.name

    def get_first_image(self):
        return self.images.first()
        


class FabricImage(models.Model):
    """
    A Django model representing images associated with fabric instances.

    Attributes:
        fabric (Fabric): The fabric instance associated with the image.
        image (ImageField): The image file uploaded for the fabric.
    """

    fabric = models.ForeignKey(
        Fabric,
        on_delete=models.CASCADE,
        help_text="The fabric instance associated with the image.",
        related_name='images'
    )
    image = models.ImageField(
        upload_to="fabrics/", help_text="The image file uploaded for the fabric."
    )

    class Meta:
        verbose_name = "Fabric Image"
        verbose_name_plural = "Fabric Images"

bold_men/fabrics/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms
from django.forms.models import inlineformset_factory
from fabrics.models import  Fabric, FabricImage


class FabricForm(forms.ModelForm):
    class Meta:
        model = Fabric
        exclude = ()
        

class FabricImageForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.TextInput(attrs={'multiple':True, 'type':'File'}))
    class Meta:
        model = FabricImage
        # To handle the fabric id in the view
        exclude = ('fabric', )


        


# FabricImageFormSet = inlineformset_factory(Fabric, FabricImage, form=forms.ModelForm, fields=['image'], extra=1, can_delete=True)

bold_men/fabrics/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
        CreateView,
        DeleteView,
        DetailView,
        ListView,
        UpdateView
)
from fabrics.models import Fabric, FabricImage
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from fabrics.forms import FabricForm, FabricImageForm 
# FabricImageFormSet

class FabricCreateView(CreateView):
    model = Fabric
    template_name = 'fabrics/fabric_form.html'
    success_url = reverse_lazy('fabrics:fabric-list')

    def get(self, request, *args, **kwargs):
        fabric_form = FabricForm()
        fabric_image_form = FabricImageForm()
        return render(request, self.template_name, {
            'fabric_form': fabric_form,
            'fabric_image_form':fabric_image_form
            })

    def post(self, request, *args, **kwargs):
        fabric_form = FabricForm(request.POST)
        fabric_image_form = FabricImageForm(request.POST, request.FILES)
        if fabric_form.is_valid():
            fabric = fabric_form.save()

            if request.FILES.getlist('image'):
                for image in request.FILES.getlist('image'):
                    FabricImage.objects.create(fabric=fabric, image=image)

            return redirect(self.success_url)
        return render(request, self.template_name, {
            'fabric_form': fabric_form,
            'fabric_image_form':fabric_image_form
            })



"""
    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)
        data  = super().get_context_data(**kwargs)
        if self.request.POST:
            data['images'] = FabricImageFormSet(self.request.POST, self.request.FILES)
        else:
                data['fabric_image_form'] = FabricImageFormSet()
        return data

    def form_valid(self, form):
        form.instance.user = self.request.user
        context = self.get_context_data()
        images = context['images']
        fabric = form.save()
        if images.is_valid():
            images.instance = fabric
            images.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        context = self.get_context_data()
        images = context['images']
        print(images)
        return self.render_to_response(self.get_context_data(form=form, images=images))
        
        

"""


# the form created is to add crispy style to it

class FabricUpdateView(UpdateView, UserPassesTestMixin, LoginRequiredMixin):
    model = Fabric
    template_name = 'fabrics/fabric_update.html'
    fields = ['name', 'description', 'price']

    # checks if there is a user logged in is the one filling the form
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
        


    def test_func(self):
        order = self.get_object()
        if self.request.user == order.user:
            return True
        return False


class FabricDeleteView(LoginRequiredMixin, DeleteView, UserPassesTestMixin):
    model = Fabric
    success_url = '/'

    def test_func(self):
        order = self.get_object()
        if self.request.user == order.user:
            return True
        return False
          

class FabricListView(ListView):
    model = Fabric
    # template_name = 'fabrics/order_list.html' # <app>/<model>_<viewtype>.html
    context_object_name = 'fabrics'
    ordering = ['name']




class FabricDetailView(DetailView):
    model = Fabric
    template_name = 'fabrics/fabric_details.html'

bold_men/fabrics/templates/fabrics/fabric_details.html
{% extends "main/base.html" %}
{% block content %}
<div class="container p-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card">
          <div class="card-body">
		  <h5 class="card-title">{{ fabric.name }}</h5>
		  <p class="card-text">{{ fabric.description }}</p>
		  <p><strong>Price:</strong> {{ fabric.price }}</p>
		
		  <h2>Images</h2>
		  {% for image in fabric.images.all %}
		  <div class="col-md-9">
			  <div class="d-flex jusify-content-between">
				  <img src="{{ image.image.url }}" class="mt-2 card-img-bottom w-100" alt="{{ fabric.name }}" width="200" height="200" loading="lazy">
			  </div>
		  </div>
		  	
		  {% endfor %}
            <p><strong>Color:</strong> Blue</p>
            <p><strong>Material:</strong> Cotton</p>
            <p><strong>Width:</strong> 60 inches</p>
            <p><strong>Length:</strong> Available in various lengths</p>
            <a href="#" class="btn btn-primary">Add to Cart</a>
            <a href="{% url 'fabrics:fabric-list'  %}" class="btn btn-secondary">Back to Fabrics</a>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

bold_men/fabrics/templates/fabrics/fabric_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main class="container py-5 ">
	<h2 class="text-center fw-normal">Create Fabric</h2>
	<form  method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ fabric_form|crispy }}
		<!-- Fabric Images -->
		{{ fabric_image_form|crispy }}


		<button type="submit" class="btn btn-primary">Save</button>
	</form>
</main>
{% endblock %}

bold_men/fabrics/templates/fabrics/fabric_list.html
{% extends "main/base.html" %}
{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4 fw-normal">Welcome to our Fabrics Store</h1>
    <div class="row">
	    {% for fabric in fabrics %}
	      <div class="col-md-3 mb-4">
		<div class="card">
		    {% with image=fabric.get_first_image  %}
			{% if image %}
				<img src="{{ image.image.url }}" class="card-img-top w-100" alt="Fabric 1" width="200" height="200"  loading="lazy">
			{% else %}
				<img src="" class="card-img-top" alt="Fabric 1">
			{% endif %}
		    {% endwith %}
		  <div class="card-body">
			  <h5 class="card-title">{{ fabric.name }}</h5>
			  <p class="card-text">{{ fabric.description }}</p>
		    <a href="{% url 'fabrics:fabric-detail' fabric.pk  %}" class="btn btn-primary">View Details</a>
		  </div>
		</div>
	      </div>
	    {% endfor %}
    </div>
</div>
{% endblock %}

bold_men/fabrics/templates/fabrics/fabric_update.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main class="container py-5 ">
	<h2 class="text-center fw-normal">Update Fabric</h2>
	<form  method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<!-- Fabric Images -->
		{{ fabric_image_form|crispy }}


		<button type="submit" class="btn btn-primary">Update</button>
	</form>
</main>
{% endblock %}