bold_men/accounts/urls.py
from accounts.views import register_client, register_employee, register_individual, user_logout, user_type_page, CustomLoginView, profile
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('', user_type_page, name='user-type'),
    path('register_client', register_client, name='reg-client' ),
    path('register_individual', register_individual, name='reg-individual' ),
    path('register_employee', register_employee, name='reg-employee' ),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('profile/', profile, name='profile'),
    path('logout/', user_logout, name='logout'),
]

bold_men/bold_men/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import HomePage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('contracts/', include('contracts.urls')),
    path('fabrics/', include('fabrics.urls')),
    path('orders/', include('orders.urls')),
    path('payments/', include('payments.urls')),
    path('measurements/', include('measurements.urls')),
    path('', HomePage.as_view(), name="home-page"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

bold_men/orders/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "orders"

urlpatterns = [
    # path(),
]

bold_men/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator
from PIL import Image


class CustomUserManager(BaseUserManager):

    # CustomUserManager methods not inherited
    def create_superuser(self, email, username, password, **other_fields):

        # setdefault gotten from django backend session
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError("Superuser must be assigned to is_staff=True")

        if other_fields.get('is_superuser') is not True:
            raise ValueError("Superuser must be assigned to is_superuser=True")

        return self.create_user(email, username, password, **other_fields)




        # making use of the create_user method in this place 


    # CustomUserManager methods not inherited
    def create_user(self, email, username, password, **other_fields):
        if not email:
            raise ValueError("You must provide an email address")

        # Using the methods from the inherited class (BaseUserManager): normalize_email, set_password
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **other_fields)
        user.set_password(password)
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    class Types(models.TextChoices):
        CLIENT = "CLIENT", "Client"
        INDIVIDUAL = "INDIVIDUAL", "Individual"
        EMPLOYEE = "EMPLOYEE", "Employee"

    email = models.EmailField(_('email address'), unique=True)
    # password has been defined at the AbstractBaseUser class
    username = models.CharField(max_length=50)
    full_name = models.CharField(_('Full Name'),max_length=50)
    type = models.CharField(max_length=15, choices=Types.choices, default=Types.INDIVIDUAL)
    date_joined = models.DateTimeField(default=timezone.now)
    bio = models.TextField(_('biography'), max_length=500, blank=True, default='')
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    #  

    is_individual = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)


    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


    def __str__(self):
        return self.username
        

class ClientManager(models.Manager):
    # client for bringing jobs of schools, bulk cloth sowing
    # in form of large, small and medium sizes with the required quantity
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(type=User.Types.CLIENT)
        return queryset
        

class Client(User):

    class Meta:
        proxy = True

    objects = ClientManager()

    def save(self, *args, **kwargs):
        self.type = User.Types.CLIENT
        self.is_client = True
        self.is_active = True
        # Overiding the save method and calling it back
        return super().save(*args, **kwargs)



class IndividualManager(models.Manager):
    # A single user account
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(type=User.Types.INDIVIDUAL)
        return queryset
        

class Individual(User):

    class Meta:
        proxy = True

    objects = IndividualManager()

    def save(self, *args, **kwargs):
        self.type = User.Types.INDIVIDUAL
        self.is_individual = True
        self.is_active = True
        # Overiding the save method and calling it back
        return super().save(*args, **kwargs)
        


class EmployeeManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(type=User.Types.EMPLOYEE)
        return queryset
        

class Employee(User):

    class Meta:
        proxy = True

    objects = EmployeeManager()

    def save(self, *args, **kwargs):
        self.type = User.Types.EMPLOYEE
        self.is_employee = True
        # can login
        self.is_active = True

        # self.is_staff can be set to true here too
        # Overiding the save method and calling it back
        return super().save(*args, **kwargs)
        

class Profile(models.Model):
    GENDER_CHOICES = [
            ('Male', "Male"),
            ('Female', "Female")
            ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    address = models.CharField(max_length=50)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=25, choices=GENDER_CHOICES)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=10)
    
    class Meta:
      #  proxy = True
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"
       #  abstract = True

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)





        

"""


class ClientProfile(Profile):
    
    class Meta:
        verbose_name = "ClientProfile"
        verbose_name_plural = "ClientProfiles"


class IndividualProfile(Profile):
    
    
    class Meta:
        verbose_name = "IndividualProfile"
        verbose_name_plural = "IndividualProfiles"


"""

bold_men/accounts/forms.py
from crispy_forms.layout import Field, Fieldset, Submit
from django import forms
from .models import Client, Individual, Employee, User, Profile
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper, Layout
from django.contrib.auth.forms import AuthenticationForm

# Adding crispy form design
# Custom admin page



class CustomLoginForm(AuthenticationForm):
    # add the necessary check there
    """
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password'}))
    """
    ...


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'username']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        exclude = ('user', 'date_of_birth',)

    ...
class ClientRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", widget=forms.EmailInput)
    full_name = forms.CharField()
    bio = forms.CharField(widget=forms.TextInput)

    class Meta:
        model = Client
        fields = ['email', 'username', 'full_name', 'bio', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
                Fieldset(
                    'Personal Information',
                    Field('email', placeholder="adeleke@gmail.com"),
                    'password1',
                    'password2',
                    ),
                Fieldset(
                    'Additional Details',
                    'username',
                    'full_name',
                    'bio',
                    ),
                Submit('submit', 'Submit', css_class='btn btn-primary')
                )
        



class IndividualRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", widget=forms.EmailInput)
    full_name = forms.CharField()
    bio = forms.CharField(widget=forms.TextInput)

    class Meta:
        model = Individual
        fields = ['email', 'username', 'full_name', 'bio', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
                Fieldset(
                    'Personal Information',
                    'email',
                    'password1',
                    'password2',
                    ),
                Fieldset(
                    'Additional Details',
                    'username',
                    'full_name',
                    'bio',
                    ),
                Submit('submit', 'Submit', css_class='btn btn-primary')
                )
        
class EmployeeRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", widget=forms.EmailInput(attrs={'placeholder': 'example@domain.com'}))
    full_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Full Name'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Tell us about yourself...'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Fieldset(
                'Account Information',
                'email',
                'username',
                'password1',
                'password2',
            ),
            Fieldset(
                'Personal Details',
                'full_name',
                'bio',
            ),
            Submit('submit', 'Register', css_class='btn btn-primary')
        )

    class Meta:
        model = Employee
        fields = ['email', 'username', 'full_name', 'bio', 'password1', 'password2']

bold_men/accounts/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import login_required
from accounts.forms import (
        ClientRegisterForm,
        IndividualRegisterForm,
        EmployeeRegisterForm,
        UserUpdateForm,
        ProfileUpdateForm,
        )
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateView
from django.contrib import messages

from fabrics.models import Fabric
from .forms import CustomLoginForm
from django.contrib.auth.views import LoginView



class HomePage(TemplateView):
    template_name = 'main/home.html'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        featured_fabrics = Fabric.objects.all()[:3]
        context['featured_fabrics'] = featured_fabrics
        return context




def user_type_page(request):
    return render(request, "accounts/user_type.html")

def register_client(request):
    if request.method == "POST":
        form = ClientRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('accounts:login')
    else:
        form = ClientRegisterForm()
    context = {'form': form}
    return render(request, "accounts/register_client.html", context)

def register_individual(request):
    if request.method == "POST":
        form = IndividualRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('accounts:login')
    else:
        form = IndividualRegisterForm()
    context = {'form': form}
    return render(request, "accounts/register_individual.html", context)

def register_employee(request):
    if request.method == "POST":
        form = EmployeeRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('accounts:login')
    else:
        form = EmployeeRegisterForm()
    context = {'form': form}
    return render(request, "accounts/register_employee.html", context)


class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    form_class = CustomLoginForm


@login_required
def user_logout(request):
    logout(request)
    return render(request, "accounts/logout.html")
    
@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('accounts:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
            'u_form': u_form,
            'p_form': p_form
            }
    return render(request, "accounts/profile.html", context)
    

bold_men/accounts/templates/accounts/edit_profile.html
{% extends "main/base.html" %}
{% block content %}
<main>
	
</main>
{% endblock %}

bold_men/accounts/templates/accounts/login.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main class="container py-5">
{% comment %}
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" value="Login" class="btn btn-primary" />
	</form>
	
{% endcomment %}
<div class="">
        <h2 class="text-center">Login Page</h2>
      <div class="">
        <!-- Login Form -->
        <form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" value="Login" class="btn btn-primary" />
	</form>
      </div>
      <div>
        <a href="#" class="btn btn-link">Forgot Password?</a>
      </div>
</div>

</main>
{% endblock %}

bold_men/accounts/templates/accounts/logout.html
{% extends "main/base.html" %}
{% block content %}
<main class="container py-5 my-5">
	<h2>You have been logged out</h2>	
	<small class="text-muted">
		<a class="btn btn-primary" href="{% url 'accounts:login' %}">Log In Again</a>
	</small>
</main>
{% endblock %}

bold_men/accounts/templates/accounts/profile.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main class="container">
    <div class="content-section my-5 pb-5">
        <div class="media">
            <img class="rounded-circle img-fluid w-25" src="{{ user.profile.image.url }}" alt="User Profile Image">
            <div class="media-body">
                <h2 class="h4">{{ user.username }}</h2>
                <p class="text-muted">{{ user.email }}</p>
            </div>
        </div>
        <!-- Add icons here -->
        <i class="bi bi-envelope"></i> <!-- Example: Email icon -->
        <i class="bi bi-phone"></i> <!-- Example: Phone icon -->
        <!-- FORM HERE -->

	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset id="$0_$0" class="">
			<legend>Profile Info</legend>
			{{ u_form|crispy }}
			{{ p_form|crispy }}
		</fieldset>

		<div class="form-group">
			<button class="btn btn-outline-info" type="submit">Update</button>
		</div>
		
	</form>
    </div>
	
</main>
{% endblock %}

bold_men/accounts/templates/accounts/register_client.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main class="container py-5">
	<div class="row justify-content-center">
		<div class="col col-md-9 col-lg-10">
			<form method="post">
				{% csrf_token %}
				{% crispy form %}
			</form>
		</div>

	</div>
</main>
{% endblock %}

bold_men/accounts/templates/accounts/register_employee.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main class="container py-5">
	<form method="post">
		{% csrf_token %}
		{% crispy form %}
	</form>
</main>
{% endblock %}

bold_men/accounts/templates/accounts/register_individual.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main class="container py-5">	
	<form method="post">
		{% csrf_token %}
		{% crispy form %}
	</form>
</main>
{% endblock %}

bold_men/accounts/templates/accounts/user_type.html
{% extends "main/base.html" %}
{% block content %}
<main class="container p-5">
	<h3 class="display-6 fw-normal mb-5">Register as a Client, Individual or an Employee:</h3>
	<div class="row g-2 row-cols-1 row-cols-md-2 row-cols-lg-3">
		<div class="col">
			<div class="card p-5 bg-dark text-white" style="width: 18rem;">
				<div class="card-body"></div>
				<h5 class="card-title">Client</h5>
				<p>Sit magni dolore dolor molestias rerum odit, perferendis Alias earum facere impedit</p>
				<a href="{% url 'accounts:reg-client'  %}" class="btn btn-primary">Message Us</a>
			</div>
		</div>
		<div class="col">
			<div class="card p-5" style="width: 18rem;">
				<div class="card-body"></div>
				<h5 class="card-title">Individual</h5>
				<p>Sit magni dolore dolor molestias rerum odit, perferendis Alias earum facere impedit</p>
				<a href="{% url  'accounts:reg-individual' %}" class="btn btn-primary">Patronize Us</a>
			</div>
		</div>
		<div class="col">
			<div class="card p-5 bg-secondary text-light" style="width: 18rem;">
				<div class="card-body"></div>
				<h5 class="card-title">Employee</h5>
				<p>A registered staff of bold men responsible for taking measurement and sending necessary details.</p>
				<a href="{% url 'accounts:reg-employee' %}" class="btn btn-primary">Join Us</a>
			</div>
		</div>
	</div>
</main>
{% endblock %}